# Generated by Django 4.1 on 2022-09-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('secretIdentity', models.CharField(max_length=200)),
                ('weaknessess', models.TextField()),
                ('strengths', models.TextField()),
                ('imageLoc', models.CharField(max_length=200)),
            ],
        ),
    ]
